menu:
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/DinoWildi'}
- {icon: 'fa-bluesky', link: 'https://bsky.app/profile/dnwildi.bsky.social'}
- {icon: 'fa-orcid', link: 'https://orcid.org/0009-0008-9076-6718'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
